### ISSUE TITLE
Reported numbers differ between Home and Dashboard pages

### ISSUE THREAD

**Issue by ajbarnes** [VA-Explorer/va_explorer#108]
**Describe the bug**
When viewing, for example, the number of overall coded VAs on the Home page and the number of coded VAs reported by the dashboard, the numbers inexplicably do not match-up. Other numbers may also inexplicably differ.

**To Reproduce**
1. Open a tab for https://va.moh.gov.zm/va_analytics/dashboard/
2. Open a tab for https://va.moh.gov.zm/
3. Observe mismatching numbers

**Expected behavior**
Reported numbers for the same statistics should be consistent across pages (preferred) or contain some explanation for why they differ.

**Screenshots (nice to have)**
![Screen Shot 2021-07-16 at 4 48 19 PM](https://user-images.githubusercontent.com/6718827/126007155-31ef539b-4cd6-43bf-8072-cba7bb985853.png)

**Desktop (please complete the following information):**
- OS: Mac
- Browser: chrome
- Version: 91.0.4472.114 (Official Build) (x86_64)

**Additional context**
The number mismatch may be explained by invalid VAs the dashboard doesn't process/count towards its own statistics but this should be explained or changed in some way to avoid confusing users.

**Comment by mboyas-mitre** [comment]
Heard again in Data Viewer Think-Aloud on 7.24.2021
