### ISSUE TITLE
Dashboard - Split top N COD into top N for each age/demographic category

### ISSUE THREAD

**Issue by mboyas-mitre** [VA-Explorer/va_explorer#139]
**Is your feature request related to a problem? Please describe.**
The dashboard currently has the Top N CODs and then splits those N out by demographic selectors.  This could be useful, but would like something else.

**Describe the solution you'd like**
Ideally, would like Top N WITHIN the demographic category.  E.g., top N for all neonate and top N for all adult.

**Describe alternatives you've considered**
Might want the ability to have both, but this new proposed solution would be more useful

**Comment by ajbarnes** [comment]
Completed by #254
