### ISSUE TITLE
Dashboard Date Filtering - more precise

### ISSUE THREAD

**Issue by mboyas-mitre** [VA-Explorer/va_explorer#142]
**Is your feature request related to a problem? Please describe.**
No problem

**Describe the solution you'd like**
Some individuals will use VA Explorer to pull information from the dashboard for quarterly reports.  The dashboard allows you to subset to the "last 3 months" which would be fine right at the time of writing the report.  However, it might be useful to allow the user to specify specific date time windows to make that report generation easier.

**Describe alternatives you've considered**

**Additional context**

**Comment by ajbarnes** [comment]
Suggestion: Default time shown is "All time", first step at adjusting is a date selector, date selector should include an option for common time(s) like "Last 30 days"

**Comment by ajbarnes** [comment]
Closed by #249
