### ISSUE TITLE
Print selected geographic location on dashboard

### ISSUE THREAD

**Issue by mboyas-mitre** [VA-Explorer/va_explorer#143]
**Is your feature request related to a problem? Please describe.**
As a data viewer, I want to be pull numbers for reports and be clear about what numbers I am pulling.

**Describe the solution you'd like**
It is unclear to me what geographic area the dashboard is focusing on sometimes, which changes the numbers in the charts I would download.  I think printing the geographic area selected in addition to having the location shown on the map would clarify this.

**Describe alternatives you've considered**

**Additional context**

**Comment by ajbarnes** [comment]
Closed as duplicate of #116
