### ISSUE TITLE
Support 'indeterminate' CoD designations

### ISSUE THREAD

**Issue by ajbarnes** [VA-Explorer/va_explorer#153]
**Is your feature request related to a problem? Please describe.**
Some causes of death may be truly indeterminate. VA Explorer currently relies on the $CAUSE1 returned by [InterVA5](https://github.com/VA-Explorer/InterVA5) which may be blank in cases of indeterminate. Currently such cases are reported as 'unknown' or left blank, which is distinctly different from cases where the CoD is 'known' to be indeterminate.

**Describe the solution you'd like**
[InterVA5](https://github.com/VA-Explorer/InterVA5) should support returning $INDET values so that VA Explorer can use it. Any changes needed to use the updated version of [InterVA5](https://github.com/VA-Explorer/InterVA5) should be implemented in this repo. Code related to cause of death assignment should account for this $INDET value and assign the string 'indeterminate' accordingly.

**Comment by mboyas-mitre** [comment]
To track an indeterminate COD, we need to look in the output of the InterVA5 service for a "CAUSE1":[" "],"LIK1":[" "], and "INDET":[100].  The plan as discussed with @ajbarnes and @babraham33 is to assign VAs that meet these criteria a COD of "Indeterminate" inside VA Explorer.  We will need to do this conditionally on InterVA5 being the selected algorithm; if/when we add future algorithms in the future, other algorithms do not have Indeterminate as a COD.
