### ISSUE TITLE
Support multiple COD algorithms in regards to multiple forms

### ISSUE THREAD

**Issue by mboyas-mitre** [VA-Explorer/va_explorer#205]
We would like to be able to run multiple algorithms within VA Explorer.  This story entails packaging multiple algorithm containers with VA Explorer all being run as services.  This story is NOT the ability to run a single VA through multiple algorithms to obtain (and compare) multiple CODs; rather, this story is supporting multiple questionnaire forms where a WHO2016 form needs to be run through one algorithm and a WHO2021 form needs to be run through a different algorithm (for example).

VA Explorer needs to maintain a mapping of what form version is supported by what algorithm.  The user will configure what algorithm is default for each form version.  Future feature requests can enable extensions of multiple algorithms being run for a single VA.

**Comment by ajbarnes** [comment]
Links #110
