### ISSUE TITLE
Resolve or track via issue, all TODOs

### ISSUE THREAD

**Issue by ajbarnes** [VA-Explorer/va_explorer#222]
**What is the expected state?**
As a VA Explorer developer I expect the code to be free of TODOs; with said TODOs either corrected or issues opened for each as needed.

**What is the actual state?**
There are currently many unresolved/untracked TODOs in the codebase.

**Relevant context**
Included below is a checklist of currently identified TODOs, along with a priority (A) = highest, (D) = lowest, and a location in the codebase (`note:`)
- [ ] (C) Migrate DHIS module to combine with export module `note:va_explorer/config/urls.py`
- [x] (D) Consider using a slimmer option than plotly for homepage visualizations `note:va_explorer/va_explorer/home/views.py`
- [x] (C) Restrict homepage visualizations to user role as appropriate - [] (interviewers only see own data) `note:va_explorer/va_explorer/home/views.py`
- [ ] (C) Remove button disable "once we get export working" `note:va_explorer/va_explorer/static/js/va_export.js`
- [x] (D) Refactor login.html to conform to DRY principle since it has lots in common with base files `note:va_explorer/va_explorer/templates/account/login.html`
- [x] (C) Determine if email confirmation will be requirement going forward and remove code users/forms.py as appropriate `note:va_explorer/va_explorer/users/forms.py`
- [x] (C) Determine if we will support more than one username going forward and remove code users/models.py as appropriate `note:va_explorer/va_explorer/users/models.py`
- [x] (C) Determine if email confirmation will be requirement going forward and remove code in users/models.py as appropriate `note:va_explorer/va_explorer/users/models.py`
- [ ] (C) Determine if username adaption to ODK is need and fix as appropriate `note:va_explorer/va_explorer/users/models.py`
- [x] (C) Convert validator functions into validator classes for users `note:va_explorer/va_explorer/users/validators.py`
- [x] (C) Determine if we will support more than one username going forward and remove code users/views.py as appropriate `note:va_explorer/va_explorer/users/views.py`
- [x] (C) Determine if email confirmation will be requirement going forward and remove code users/forms.py as appropriate `note:va_explorer/va_explorer/users/views.py`
- [ ] (C) Change redirect after password reset from about page to home page `note:va_explorer/va_explorer/users/views.py`
- [ ] (C) Change success_url after password reset from about page to home page `note:va_explorer/va_explorer/users/views.py`
- [ ] (D) Extract BrowserTests class out into pytest fixture to share across tests `note:va_explorer/va_explorer/users/tests/test_user_create_browser.py`
- [x] (D) Convert BrowserTests setUpClass to be headless in order to run on CI `note:va_explorer/va_explorer/users/tests/test_user_create_browser.py`
- [ ] (D) Determine if view initialization can be extracted out into a class-scoped fixture and act accordingly `note:va_explorer/users/tests/test_views.py`
- [ ] (D) Determine if tests should inject middleware and become an integration test and act accordingly `note:va_explorer/users/tests/test_views.py`
- [x] (C) Fix issue where downloaded csv code does not actually set filename for unknown reason `note:va_explorer/utils/file_io.py`
- [x] (C) Make geo_filter granularity work for more than one assigned region or create ticket instead `note:va_explorer/va_analytics/dash_apps/va_dashboard.py`

**Comment by Tyler-Manderfield** [comment]
@ajbarnes 

**The following seemed like quick wins:**
- (C) Change redirect after password reset from about page to home page note:va_explorer/va_explorer/users/views.py

- (C) Change success_url after password reset from about page to home page note:va_explorer/va_explorer/users/views.py

- (C) Remove button disable "once we get export working" note:va_explorer/va_explorer/static/js/va_export.js

** I ran out of time on the remaining unchecked items, as I was having a bit more trouble adding context to them for an issue since I was less familiar with them (tests, DHIS and ODK). **
Also, apologies if some of the ones I added sounded a bit vague.
I used the branch: "222-remove-TODOs" to remove the comments from the ones I checked above.
