### ISSUE TITLE
Determine if multiple usernames allowed for user

### ISSUE THREAD

**Issue by Tyler-Manderfield** [VA-Explorer/va_explorer#225]
**What is the expected state?**
Should we decide that multiple usernames for a user are acceptable, the code should be updated to reflect the change.

**What is the actual state?**
The code currently assumes only one username is permitted.

**Relevant context**
- **```va_explorer/va_explorer/users/models.py```**
	The methods of ```set_va_username``` and ```get_va_username``` will need to be altered if multiple usernames are permitted.
- **```va_explorer/va_explorer/users/views.py```**
 Within the ```get_initial``` function, we will need to alter the line setting ```initial['va_username']``` to account for more than one username.

**Comment by ajbarnes** [comment]
OBE, deciding to only support 1 username
