### ISSUE TITLE
Replace Plotly in Home visualization

### ISSUE THREAD

**Issue by Tyler-Manderfield** [VA-Explorer/va_explorer#229]
**What is the expected state?**
Homepage visualization is quick and displays the information it currently does but less bulky than Plotly.

**What is the actual state?**
We are currently using Plotly to display homepage visualizations, but this is a bit clunky for the simplistic data it shows.

**Relevant context**
- **```va_explorer/va_explorer/home/views.py```**

**Comment by ajbarnes** [comment]
Closed by #237
