### ISSUE TITLE
crontab error

### ISSUE THREAD

**Issue by QollinsOchieng** [VA-Explorer/va_explorer#8]
I am getting this error: in validators.py
AttributeError: module 'crontab' has no attribute 'CronSlices'

**Comment by pkmitre** [comment]
This seems likely to be related to the use of the Celery package. Is the error occurring when you start the application with `runserver`? Or at some other point?

**Comment by QollinsOchieng** [comment]
When I start the application with `runsever`

**Comment by QollinsOchieng** [comment]
Please update this file and include django.contrib.admin in list of INSTALLED_APPS

Currently its not included

https://github.com/VA-Explorer/va_explorer/blob/master/config/settings/base.py

**Comment by QollinsOchieng** [comment]
So I picked this file and the issue about crontab was resolved

https://raw.githubusercontent.com/peak6/python-crontab/master/crontab.py

**Comment by pkmitre** [comment]
Thanks for the continued feedback!
